version: '2'

volumes:
  nginx_logs:
    external:
      name: proxy_nginx_logs
  base_atom_data:
  base_schemas:
  geoserver_data:
  awstats_result:  
    external:
      name: proxy_awstats_result

services:
  db:
    restart: always
    build: database
    ports:
      - "5432:5432"
    environment:
      DEBUG: "false"
      
  geoserver:
    restart: always
    build:
      context: ./geoserver
    environment: 
      VIRTUAL_HOST: "inspire.rdw.local"
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      TOMCAT_EXTRAS: "false"
      GEOSERVER_PASSWORD: ${GEOSERVER_PASSWORD}
      PROXY_BASE_URL: "http://inspire.rdw.local/"
    links: 
      - db
    ports:
      - "8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
  ogr2ogr:
    restart: always
    build:
      context: ./ogr2ogr
    tty: true
    links: 
      - db
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - base_atom_data:/usr/share/nginx/html/www/download
      - base_schemas:/usr/share/nginx/html/schemas
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin:/usr/host/bin

  hale:
    build: hale
    links:
      - db
    volumes:
      - base_atom_data:/usr/share/nginx/html/www/download
            
networks:
  default:
    external:
      name: rdw-inspire
