version: '2'

volumes:
  awstats_result:
  base_atom_data:
  db_data:
  geoserver_data:
  nginx_logs:

services:
  nginx:
    build: nginx
    restart: always
    environment:
      ENABLE_IPV6: "true"
      VIRTUAL_HOST: "rdw-inspire.idgis.local,inspire.rdw.local"
    volumes:
      - base_atom_data:/usr/share/nginx/html/www/download
      - nginx_logs:/var/log/nginx
    networks:
      - rdw-inspire
      - proxy

  awstats:
    build: awstats
    restart: always
    tty: true
    volumes:
      - awstats_result:/usr/lib/cgi-bin
      - nginx_logs:/var/log/nginx
    networks:
      - rdw-inspire

  db:
    build: database
    restart: always
    environment:
      DEBUG: "false"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rdw-inspire
      
  geoserver:
    build: geoserver
    restart: always
    environment:
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      TOMCAT_EXTRAS: "false"
      GEOSERVER_PASSWORD: ${GEOSERVER_PASSWORD}
      PROXY_BASE_URL: "http://inspire.rdw.local/"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    networks:
      - rdw-inspire

  ogr2ogr:
    build: ogr2ogr
    restart: always
    tty: true
    environment:
      HALE_IMAGE_VERSION: "2.1.4"
      NETWORK_NAME: "rdw-inspire"
      NGINX_CONTAINER: "rdw_nginx_1"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - base_atom_data:/usr/share/nginx/html/www/download
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin:/usr/host/bin
    networks:
      - rdw-inspire

  backup:
    image: idgis/file-backup
    restart: always
    environment:
      SFTP_USER: ""
      SFTP_PASSWORD: ""
      SFTP_HOST: ""
      SFTP_PORT: ""
      BACKUP_NAME: "backup/rdw"
    volumes:
      - awstats_result:/backup/awstats_result
      - base_atom_data:/backup/base_atom_data
      - geoserver_data:/backup/geoserver_data
      - nginx_logs:/backup/nginx_logs
    networks:
      - rdw-inspire
            
networks:
  rdw-inspire:
    external: true
  proxy:
    external: true
