version: '2'

volumes:
  nginx_logs:
  base_atom_data:
  geoserver_data:

services:
  db:
    build: database
    ports:
      - "5432:5432"
    expose:
     - "5432"
    environment:
      DEBUG: "false"
      
  geoserver:
    build:
      context: ./geoserver
    environment: 
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      TOMCAT_EXTRAS: "false"
      GEOSERVER_PASSWORD: "6KcEadyGVwGrtxKG"
      PROXY_BASE_URL: "http://rdw-inspire.idgis.nl/"
    links: 
      - db
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
  ogr2ogr:
    build:
      context: ./ogr2ogr
    tty: true
    links: 
      - db
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - base_atom_data:/usr/share/nginx/html/www/download

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    volumes:
      - nginx_logs:/var/log/nginx
      - base_atom_data:/usr/share/nginx/html/www/download
            
networks:
  default:
    external:
      name: rdw-inspire