version: '2'

volumes:
  nginx_logs:
  base_atom_data:
  geoserver_data:
  awstats_result:  

services:
  db:
    build: database
    ports:
      - "5432"
    environment:
      DEBUG: "false"
      
  geoserver:
    build:
      context: ./geoserver
    environment: 
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
      TOMCAT_EXTRAS: "false"
      GEOSERVER_PASSWORD: ${GEOSERVER_PASSWORD}
      PROXY_BASE_URL: "http://inspire.rdw.nl/"
    links: 
      - db
    ports:
      - "8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
  ogr2ogr:
    build:
      context: ./ogr2ogr
    tty: true
    links: 
      - db
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - base_atom_data:/usr/share/nginx/html/www/download

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    volumes:
      - nginx_logs:/var/log/nginx
      - base_atom_data:/usr/share/nginx/html/www/download

  awstats:
    build:
      context: ./awstats
    tty: true
    ports:
      - "80"
    volumes:
      - nginx_logs:/var/log/nginx
      - awstats_result:/usr/lib/cgi-bin
            
  backup:
    build:
      context: ./backup
    tty: true
    environment:
      - SFTP_USER=${BACKUP_SFTP_USER}
      - SFTP_PASSWORD=${BACKUP_SFTP_PASSWORD}
      - SFTP_HOST=${BACKUP_SFTP_HOST}
      - SFTP_PORT=${BACKUP_SFTP_PORT}
      - BACKUP_NAME=backup/rdw-inspire    
    volumes:
      - nginx_logs:/var/log/nginx
      - awstats_result:/usr/lib/cgi-bin
      - base_atom_data:/usr/share/nginx/html/www/download
      - geoserver_data:/opt/geoserver/data_dir
            
networks:
  default:
    external:
      name: rdw-inspire